"""
CyberShield AI - Autonomous Defense API

Orchestrates:
    XGBoost -> PPO V5 -> Blockchain

The network context used for PPO is generated by the existing
CyberShield network simulator. This is controlled simulation,
not live network traffic.
"""

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field

from app.services.xgboost_service import xgboost_service
from ai.rl.simulation.network_simulator import NetworkSimulator
from ai.integration.xgboost_ppo_blockchain import cybershield_integration


router = APIRouter(
    prefix="/api/defense",
    tags=["Autonomous Defense"]
)


class DefenseRequest(BaseModel):

    features: list[float] = Field(
        ...,
        min_length=40,
        max_length=40,
        description="Exactly 40 numerical features required by XGBoost"
    )

    source_ip: str = Field(
        ...,
        description="Source IP address of the network traffic"
    )


@router.post("/analyze")
def analyze_threat(request: DefenseRequest):

    try:

        # -------------------------------------------------------------
        # 1. Run XGBoost first to identify the attack class.
        # -------------------------------------------------------------

        xgb_result = xgboost_service.predict(
            request.features
        )


        # -------------------------------------------------------------
        # 2. Generate controlled network context for PPO.
        #
        # The attack type comes from the REAL XGBoost prediction.
        # Packet rate, byte rate, severity and active threats are
        # simulated by the existing NetworkSimulator.
        # -------------------------------------------------------------

        simulator = NetworkSimulator(
            seed=42
        )

        scenario = simulator.generate_scenario(
            attack_type=xgb_result["predicted_class"]
        )


        # -------------------------------------------------------------
        # 3. Run the existing XGBoost -> 26D -> PPO -> Blockchain
        #    integration.
        #
        # XGBoost is run again inside the existing integration service
        # so the integration remains independently usable.
        # -------------------------------------------------------------

        result = cybershield_integration.predict_and_record(
            features=request.features,
            source_ip=request.source_ip,
            threat_severity=scenario.threat_severity,
            packet_rate=scenario.packet_rate,
            byte_rate=scenario.byte_rate,
            active_threats=scenario.active_threats,
            available_resources=1.0,
            previous_action=0,
        )


        # -------------------------------------------------------------
        # 4. Add controlled network context to the response.
        # -------------------------------------------------------------

        result["network_context"] = {
            "packet_rate": scenario.packet_rate,
            "byte_rate": scenario.byte_rate,
            "active_threats": scenario.active_threats,
            "threat_severity": scenario.threat_severity,
        }

        return result


    except ValueError as error:

        raise HTTPException(
            status_code=400,
            detail=str(error)
        )


    except Exception as error:

        raise HTTPException(
            status_code=500,
            detail=f"Autonomous defense analysis failed: {str(error)}"
        )